<?php

/**
 * BaseVentas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categoria_id
 * @property string $titulo
 * @property string $categorias
 * @property text $contenido
 * @property text $disponible_para
 * @property boolean $is_active
 * @property string $thumbnail
 * @property integer $position
 * @property CategoriasVentas $CategoriasVentas
 * @property Doctrine_Collection $VentasGaleria
 * 
 * @method integer             getCategoriaId()      Returns the current record's "categoria_id" value
 * @method string              getTitulo()           Returns the current record's "titulo" value
 * @method string              getCategorias()       Returns the current record's "categorias" value
 * @method text                getContenido()        Returns the current record's "contenido" value
 * @method text                getDisponiblePara()   Returns the current record's "disponible_para" value
 * @method boolean             getIsActive()         Returns the current record's "is_active" value
 * @method string              getThumbnail()        Returns the current record's "thumbnail" value
 * @method integer             getPosition()         Returns the current record's "position" value
 * @method CategoriasVentas    getCategoriasVentas() Returns the current record's "CategoriasVentas" value
 * @method Doctrine_Collection getVentasGaleria()    Returns the current record's "VentasGaleria" collection
 * @method Ventas              setCategoriaId()      Sets the current record's "categoria_id" value
 * @method Ventas              setTitulo()           Sets the current record's "titulo" value
 * @method Ventas              setCategorias()       Sets the current record's "categorias" value
 * @method Ventas              setContenido()        Sets the current record's "contenido" value
 * @method Ventas              setDisponiblePara()   Sets the current record's "disponible_para" value
 * @method Ventas              setIsActive()         Sets the current record's "is_active" value
 * @method Ventas              setThumbnail()        Sets the current record's "thumbnail" value
 * @method Ventas              setPosition()         Sets the current record's "position" value
 * @method Ventas              setCategoriasVentas() Sets the current record's "CategoriasVentas" value
 * @method Ventas              setVentasGaleria()    Sets the current record's "VentasGaleria" collection
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVentas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ventas');
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('categorias', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Actriz/Conductora',
             'length' => 255,
             ));
        $this->hasColumn('contenido', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('disponible_para', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('thumbnail', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin_imagen.jpg',
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoriasVentas', array(
             'local' => 'categoria_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('VentasGaleria', array(
             'local' => 'id',
             'foreign' => 'ventas_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titulo',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}