<?php

/**
 * BasePublicaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categoria_id
 * @property string $titulo
 * @property text $contenido
 * @property text $descripcion_corta
 * @property boolean $is_active
 * @property string $thumbnail
 * @property integer $position
 * @property CategoriasPublicaciones $CategoriasPublicaciones
 * @property Doctrine_Collection $PublicacionesGaleria
 * 
 * @method integer                 getCategoriaId()             Returns the current record's "categoria_id" value
 * @method string                  getTitulo()                  Returns the current record's "titulo" value
 * @method text                    getContenido()               Returns the current record's "contenido" value
 * @method text                    getDescripcionCorta()        Returns the current record's "descripcion_corta" value
 * @method boolean                 getIsActive()                Returns the current record's "is_active" value
 * @method string                  getThumbnail()               Returns the current record's "thumbnail" value
 * @method integer                 getPosition()                Returns the current record's "position" value
 * @method CategoriasPublicaciones getCategoriasPublicaciones() Returns the current record's "CategoriasPublicaciones" value
 * @method Doctrine_Collection     getPublicacionesGaleria()    Returns the current record's "PublicacionesGaleria" collection
 * @method Publicaciones           setCategoriaId()             Sets the current record's "categoria_id" value
 * @method Publicaciones           setTitulo()                  Sets the current record's "titulo" value
 * @method Publicaciones           setContenido()               Sets the current record's "contenido" value
 * @method Publicaciones           setDescripcionCorta()        Sets the current record's "descripcion_corta" value
 * @method Publicaciones           setIsActive()                Sets the current record's "is_active" value
 * @method Publicaciones           setThumbnail()               Sets the current record's "thumbnail" value
 * @method Publicaciones           setPosition()                Sets the current record's "position" value
 * @method Publicaciones           setCategoriasPublicaciones() Sets the current record's "CategoriasPublicaciones" value
 * @method Publicaciones           setPublicacionesGaleria()    Sets the current record's "PublicacionesGaleria" collection
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublicaciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publicaciones');
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('contenido', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion_corta', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('thumbnail', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin_imagen.jpg',
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoriasPublicaciones', array(
             'local' => 'categoria_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('PublicacionesGaleria', array(
             'local' => 'id',
             'foreign' => 'publicacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titulo',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}