<?php

/**
 * BaseTalento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categoria_id
 * @property string $titulo
 * @property text $contenido
 * @property text $actualmente
 * @property string $pagina_web
 * @property string $twitter
 * @property boolean $is_active
 * @property string $thumbnail
 * @property integer $position
 * @property CategoriasTalento $CategoriasTalento
 * @property Doctrine_Collection $TalentoGaleria
 * 
 * @method integer             getCategoriaId()       Returns the current record's "categoria_id" value
 * @method string              getTitulo()            Returns the current record's "titulo" value
 * @method text                getContenido()         Returns the current record's "contenido" value
 * @method text                getActualmente()       Returns the current record's "actualmente" value
 * @method string              getPaginaWeb()         Returns the current record's "pagina_web" value
 * @method string              getTwitter()           Returns the current record's "twitter" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method string              getThumbnail()         Returns the current record's "thumbnail" value
 * @method integer             getPosition()          Returns the current record's "position" value
 * @method CategoriasTalento   getCategoriasTalento() Returns the current record's "CategoriasTalento" value
 * @method Doctrine_Collection getTalentoGaleria()    Returns the current record's "TalentoGaleria" collection
 * @method Talento             setCategoriaId()       Sets the current record's "categoria_id" value
 * @method Talento             setTitulo()            Sets the current record's "titulo" value
 * @method Talento             setContenido()         Sets the current record's "contenido" value
 * @method Talento             setActualmente()       Sets the current record's "actualmente" value
 * @method Talento             setPaginaWeb()         Sets the current record's "pagina_web" value
 * @method Talento             setTwitter()           Sets the current record's "twitter" value
 * @method Talento             setIsActive()          Sets the current record's "is_active" value
 * @method Talento             setThumbnail()         Sets the current record's "thumbnail" value
 * @method Talento             setPosition()          Sets the current record's "position" value
 * @method Talento             setCategoriasTalento() Sets the current record's "CategoriasTalento" value
 * @method Talento             setTalentoGaleria()    Sets the current record's "TalentoGaleria" collection
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTalento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('talento');
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('contenido', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('actualmente', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('pagina_web', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('twitter', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('thumbnail', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin_imagen.jpg',
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoriasTalento', array(
             'local' => 'categoria_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('TalentoGaleria', array(
             'local' => 'id',
             'foreign' => 'publicacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titulo',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}