<?php

/**
 * BaseCategoriasVentas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bloque
 * @property string $categoria
 * @property Doctrine_Collection $Ventas
 * 
 * @method integer             getBloque()    Returns the current record's "bloque" value
 * @method string              getCategoria() Returns the current record's "categoria" value
 * @method Doctrine_Collection getVentas()    Returns the current record's "Ventas" collection
 * @method CategoriasVentas    setBloque()    Sets the current record's "bloque" value
 * @method CategoriasVentas    setCategoria() Sets the current record's "categoria" value
 * @method CategoriasVentas    setVentas()    Sets the current record's "Ventas" collection
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoriasVentas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categorias_ventas');
        $this->hasColumn('bloque', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('categoria', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ventas', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'categoria',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}