<?php

/**
 * BasePublicacionesNewsletters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $template_id
 * @property string $titulo
 * @property text $contenido
 * @property integer $tipo_archivo
 * @property string $archivo
 * @property string $thumbnail
 * @property boolean $is_active
 * @property integer $position
 * @property TemplatesNewsletters $TemplatesNewsletters
 * 
 * @method integer                  getTemplateId()           Returns the current record's "template_id" value
 * @method string                   getTitulo()               Returns the current record's "titulo" value
 * @method text                     getContenido()            Returns the current record's "contenido" value
 * @method integer                  getTipoArchivo()          Returns the current record's "tipo_archivo" value
 * @method string                   getArchivo()              Returns the current record's "archivo" value
 * @method string                   getThumbnail()            Returns the current record's "thumbnail" value
 * @method boolean                  getIsActive()             Returns the current record's "is_active" value
 * @method integer                  getPosition()             Returns the current record's "position" value
 * @method TemplatesNewsletters     getTemplatesNewsletters() Returns the current record's "TemplatesNewsletters" value
 * @method PublicacionesNewsletters setTemplateId()           Sets the current record's "template_id" value
 * @method PublicacionesNewsletters setTitulo()               Sets the current record's "titulo" value
 * @method PublicacionesNewsletters setContenido()            Sets the current record's "contenido" value
 * @method PublicacionesNewsletters setTipoArchivo()          Sets the current record's "tipo_archivo" value
 * @method PublicacionesNewsletters setArchivo()              Sets the current record's "archivo" value
 * @method PublicacionesNewsletters setThumbnail()            Sets the current record's "thumbnail" value
 * @method PublicacionesNewsletters setIsActive()             Sets the current record's "is_active" value
 * @method PublicacionesNewsletters setPosition()             Sets the current record's "position" value
 * @method PublicacionesNewsletters setTemplatesNewsletters() Sets the current record's "TemplatesNewsletters" value
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublicacionesNewsletters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publicaciones_newsletters');
        $this->hasColumn('template_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('contenido', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_archivo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 1,
             ));
        $this->hasColumn('archivo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('thumbnail', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'sin_imagen.jpg',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TemplatesNewsletters', array(
             'local' => 'template_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titulo',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}