<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/23 09:51:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jerryml_page',
  'username' => 'jerryml_jerryml',
  'password' => 'j3rrimlc0m',
  'persistent' => true,
  'name' => 'doctrine',
)),);
