<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/23 09:51:08
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#000000',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => false,
  'library' => 'gd_mime_type',
),
  'app_twitter_consumer_key' => 'j331Eo9FIEqglu2e2waE2w',
  'app_twitter_consumer_secret' => 'PhZQYDS2E4Ys8dMAqwyX9VVG3lpLcKUbN0sIsa4sU0M',
  'app_twitter_access_token' => '179341683-1MLB4HXvvnU7ewFGI9xQgRo2R68FNxCKDRLBEyM9',
  'app_twitter_access_token_secret' => 'iE0zVv0kvUaBZrxTPLVLocaSezjosteM1DN0iVWdnQ',
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'Backend Jerry ML',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
));
