<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/03/23 09:51:09
$this->security = array (
  'viewnewsletter' => 
  array (
    'is_secure' => true,
  ),
  'enviarnewsletter' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
