<?php

/**
 * CategoriasTalento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class CategoriasTalento extends BaseCategoriasTalento
{
    public function __toString() {
       return sprintf("%s",$this->getCategoria());
    }
}
