<?php

/**
 * CategoriasPublicaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Dioner911
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class CategoriasPublicaciones extends BaseCategoriasPublicaciones
{
   public function __toString() {
       return sprintf("%s",$this->getCategoria());
   }
   
}
