<?php

/**
 * MovimientosNewslettersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovimientosNewslettersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovimientosNewslettersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovimientosNewsletters');
    }
}