<?php

/**
 * Publicaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Dioner911
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */

class Publicaciones extends BasePublicaciones
{
    public function __toString() {
        return $this->getTitulo();
    }
    
    public function getCategoriaSlug(){
        return $this->getCategoriasPublicaciones()->getSlug();
    }
    
    public function getThumbnailValid(){
        $file=$this->getThumbnail();
        if(file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/thumbnails/'.$file)){
           return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/thumbnails/'.$file;
        }elseif(strlen($file)==0){
           $registro_galeria=Doctrine_Core::getTable('PublicacionesGaleria')->getPrimerArchivoPorPublicacion($this->getId());
           if(!$registro_galeria==null){
              $registro_galeria->getThumbnailValid(); 
              $this->setThumbnail($registro_galeria->getThumbnail());
              parent::save();
              $this->getThumbnailValid();
           }else{
              return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/thumbnails/bg_negro.png'; 
           }
        }else{
           return $this->getThumbnail();
        } 
    }
    
    public function getHtmlThumbnail(){
            return sprintf(<<<EOF
<div class="contenedor-archivo-galeria"> 
<img src="%s" />
</div>                    
EOF
    ,$this->getThumbnailValid());


     }
    public function getTituloCorto($max=15){
        return sfRichSys::cut_string($this->getTitulo(),$max);
    }
    public function getTituloCortoBackend($max=15){
        return substr($this->getTitulo(),0,$max);
    }
     
    public function getContenidoCorto($max=150){
        //$texto=htmlentitites($this->getContenido());
        $texto = strip_tags($this->getContenido());
        //$texto=  str_replace("&amp;", "&", $texto);
        return sfRichSys::cut_string2($texto,$max);
    }
    
    public function getContenidoMediano($max=700){
        //$texto=htmlentitites($this->getContenido());
        $texto = strip_tags($this->getContenido());
        //$texto=  str_replace("&amp;", "&", $texto);
        return sfRichSys::cut_string($texto,$max);
    }
    public function  delete(Doctrine_Connection $conn = null) {
        /*$index = Doctrine_Core::getTable('Publicaciones')->getLuceneIndex();
 
        if ($hit = $index->find('pk:'.$this->getId()))
        {
            $index->delete($hit->id);
        }*/

        return parent::delete($conn);
    }
    
    public function save(Doctrine_Connection $conn = null) {
        if(!$this->isNew()){
            $registro_galeria=Doctrine_Core::getTable('PublicacionesGaleria')->getPrimerArchivoPorPublicacion($this->getId());
            if(!$registro_galeria==null){
                $this->setThumbnail($registro_galeria->getThumbnail());
            }
        }
        if(!$this->getPosition()){
            $this->setPosition(Doctrine_Core::getTable('Publicaciones')->getMaximo());
        }
        
        /*$conn = $conn ? $conn : Doctrine_Core::getTable('Publicaciones')->getConnection();
        $conn->beginTransaction();
        try
        {
            $ret = parent::save($conn);

            $this->updateLuceneIndex();

            $conn->commit();

            return $ret;
        }
        catch (Exception $e)
        {
            $conn->rollBack();
            throw $e;
        }*/
        parent::save($conn);
        
    }
    
    public function update(){
        parent::save();
    }
    
    public function updateLuceneIndex()
    {
        $index = Doctrine_Core::getTable('Publicaciones')->getLuceneIndex();
 
        // remove an existing entry
        if ($hit = $index->find('pk:'.$this->getId()))
        {
            $index->delete($hit->id);
        }

        // don't index non-activated publication
        if (!$this->getIsActive())
        {
            return;
        }

        $doc = new Zend_Search_Lucene_Document();

        // store job primary key URL to identify it in the search results
        $doc->addField(Zend_Search_Lucene_Field::UnIndexed('pk', $this->getId()));

        // index job fields
        $doc->addField(Zend_Search_Lucene_Field::UnStored('position', $this->getPosition(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('titulo', $this->getTitulo(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('contenido', $this->getContenido(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('categoria', $this->getCategoriasPublicaciones()->getCategoria(), 'utf-8'));

        // add job to the index
        $index->addDocument($doc);
        $index->commit();
    }
    
}
