<?php

/**
 * Talento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Talento extends BaseTalento
{
    public function __toString() {
        return $this->getTitulo();
    }
    
    public function getCategoriaSlug(){
        return $this->getCategoriasPublicaciones()->getSlug();
    }
    
    public function getThumbnailValid(){
        $file=$this->getThumbnail();
        if(file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/talentos/'.$file)){
           return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/talentos/'.$file;
        }elseif($file=='sin_imagen.jpg'){
            
            return "";
            
           $registro_galeria=Doctrine_Core::getTable('TalentoGaleria')->getPrimerArchivoPorPublicacion($this->getId());
           if(!$registro_galeria==null){
              $registro_galeria->getThumbnailValid(); 
              $this->setThumbnail($registro_galeria->getArchivo());
              parent::save();
              $this->getThumbnailValid();
           }else{
              return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/thumbnails/bg_negro.png'; 
           }
        }elseif(!file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/talentos/'.$file)){
            sfRichSys::crearThumbnailTalento(sfConfig::get('sf_upload_dir').'/publicaciones/',$file,$this->isNew());
            return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/talentos/'.$file;
        }else{
           return $this->getThumbnail();
        } 
    }

    public function getArchivoValid(){
        $file=$this->getThumbnail();
        if(file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/thumbnails/'.$file)){
           return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/thumbnails/'.$file;
        }elseif(!file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/thumbnails/'.$file)){
            sfRichSys::crearThumbnailTalentoColor(sfConfig::get('sf_upload_dir').'/publicaciones/',$file,$this->isNew());
            return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/thumbnails/'.$file;
        }elseif($file=='sin_imagen.jpg'){
           $registro_galeria=Doctrine_Core::getTable('TalentoGaleria')->getPrimerArchivoPorPublicacion($this->getId());
           if(!$registro_galeria==null){
              $registro_galeria->getThumbnailValid(); 
              $this->setThumbnail($registro_galeria->getArchivo());
              parent::save();
              $this->getThumbnailValid();
           }else{
              return "http://".$_SERVER['HTTP_HOST'].'/uploads/publicaciones/thumbnails/bg_negro.png'; 
           }
        }else{
           return $this->getThumbnail();
        } 
    }
    
    public function getHtmlThumbnail(){
            return sprintf(<<<EOF
<div class="contenedor-archivo-galeria"> 
<img src="%s" />
</div>                    
EOF
    ,$this->getThumbnailValid());


     }
     public function getPaginaWebSinHttp(){
         $paginaWeb=$this->getPaginaWeb();
         $isHttp=substr($paginaWeb,0,7);
         if($isHttp=="http://"){
             return substr($paginaWeb,7,strlen($paginaWeb)-7);
         }else{
             return $paginaWeb;
         }
     }
     
     /*
     * Para crear la ruta para render la imagen
     * /imagenes/:path/:width/:heigth/:imagen.:sf_format
     */
    public function getRenderImagen($width,$height){
        $file=$this->getThumbnail();
        if(file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/'.$file)){
           return '/imagenes/publicaciones/'.$width.'/'.$height.'/'.$file;
        }else{
           return '/imagenes/publicaciones/talento/'.$width.'/'.$height.'/'.$this->getThumbnail();
        }
        
    }
    
    public function getRenderGrayscaleImagen($width,$height){
        $file=$this->getThumbnail();
        if(file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/'.$file)){
           return '/imagenes/grayscale/publicaciones/'.$width.'/'.$height.'/'.$file;
        }else{
           return '/imagenes/grayscale/publicaciones/talento/'.$width.'/'.$height.'/'.$this->getThumbnail();
        }
        
    }
     
    public function getTituloCorto($max=15){
        return sfRichSys::cut_string($this->getTitulo(),$max);
    }
    public function getTituloCortoBackend($max=15){
        $titulo=$this->getTitulo();
        return substr($titulo,0,$max);
    } 
    public function getContenidoCorto($max=150){
        $texto=strip_tags($this->getContenido());
        return sfRichSys::cut_string($texto,$max);
    }
    public function getContenidoMediano($max=700){
        $texto=strip_tags($this->getContenido());
        return sfRichSys::cut_string($texto,$max);
    }
    
    public function getDescripcionCortaValid(){
        if(!$this->getDescripcionCorta()){
            return $this->getContenidoMediano();
        }else{
            return $this->getDescripcionCorta();
        }
    }
    
    
    public function  delete(Doctrine_Connection $conn = null) {
        return parent::delete($conn);
        $thumbnail=$this->getThumbnail();
        if(file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/talentos/'.$thumbnail)){
            unlink(sfConfig::get('sf_upload_dir').'/publicaciones/talentos/'.$thumbnail);   
        }
        if(file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/'.$thumbnail)){
            unlink(sfConfig::get('sf_upload_dir').'/publicaciones/'.$thumbnail);   
        }
    }
    
    public function save(Doctrine_Connection $conn = null) {
        /*if(!$this->isNew()){
            $registro_galeria=Doctrine_Core::getTable('TalentoGaleria')->getPrimerArchivoPorPublicacion($this->getId());
            if(!$registro_galeria==null){
                $this->setThumbnail($registro_galeria->getThumbnail());
            }
        }*/
        $thumbnail=$this->getThumbnail();
        if($thumbnail!="sin_imagen.jpg"){
            if(!file_exists(sfConfig::get('sf_upload_dir').'/publicaciones/talentos/'.$thumbnail)){
            sfRichSys::crearThumbnailTalento(sfConfig::get('sf_upload_dir').'/publicaciones/',$thumbnail,$this->isNew());
            }
        }
        if(!$this->getPosition()){
            $this->setPosition(Doctrine_Core::getTable('Talento')->getMaximo());
        }
        
        parent::save($conn);
        
        
    }
    public function update(){
        parent::save();
    }
    
    public function updateLuceneIndex()
    {
        $index = TalentoTable::getLuceneIndex();
 
        // remove an existing entry
        if ($hit = $index->find('pk:'.$this->getId()))
        {
            $index->delete($hit->id);
        }

        // don't index non-activated publication
        if (!$this->getIsActive())
        {
            return;
        }

        $doc = new Zend_Search_Lucene_Document();

        // store job primary key URL to identify it in the search results
        $doc->addField(Zend_Search_Lucene_Field::UnIndexed('pk', $this->getId()));

        // index job fields
        $doc->addField(Zend_Search_Lucene_Field::UnStored('position', $this->getPosition(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('titulo', $this->getTitulo(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('contenido', $this->getContenido(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('categoria', $this->getCategoriasTalento()->getCategoria(), 'utf-8'));

        // add job to the index
        $index->addDocument($doc);
        $index->commit();
    }
}