<?php

/**
 * Ventas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    JerryML
 * @subpackage model
 * @author     Dioner911
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Ventas extends BaseVentas
{
    public function __toString() {
        return $this->getTitulo();
    }
    public function getThumbnailValid(){
        $tipos=Doctrine_Core::getTable('VentasGaleria')->getTiposArchivo();
        $thumbnail=$this->getThumbnail();
        switch($this->getTipoArchivoValid()){
            case $tipos['Imagen']:
                if(file_exists(sfConfig::get('sf_upload_dir').'/ventas/thumbnails/'.$thumbnail) && strlen($thumbnail)){
                    return "http://".$_SERVER['HTTP_HOST'].'/uploads/ventas/thumbnails/'.$thumbnail;
                }elseif(file_exists(sfConfig::get('sf_upload_dir').'/ventas/'.$thumbnail)){
                    if(file_exists(sfConfig::get('sf_upload_dir').'/ventas/'.$thumbnail)){
                        sfRichSys::crearThumbnailVentas(sfConfig::get('sf_upload_dir').'/ventas/',$thumbnail,$this->isNew());
                    }else{
                        $this->setThumbnail("sin_imagen.jpg");  
                    }
                    return "http://".$_SERVER['HTTP_HOST'].'/uploads/ventas/thumbnails/'.$this->getThumbnail();
                }else{
                    return "http://".$_SERVER['HTTP_HOST'].'/uploads/ventas/thumbnails/sin_imagen.jpg';
                }    
                break;
            case $tipos['Swf']:
                return "http://".$_SERVER['HTTP_HOST'].'/uploads/ventas/SWF.png';
                break;
            default:
                return $this->getThumbnail();
        }
    }
    
    
    public function getArchivoView(){
        $ventas=$this;
        $categoria=$ventas->getCategoriaId();
        switch($categoria){
            case 1:
                $respuesta='<img src="http://'.$_SERVER['HTTP_HOST'].'/uploads/ventas/'.$ventas->getThumbnail().'" width="130" height="130" title="'.$ventas->getTitulo().'"/>';
                break;
            case 2:
                $respuesta='<img src="http://'.$_SERVER['HTTP_HOST'].'/uploads/ventas/'.$ventas->getThumbnail().'" width="161" height="354" title="'.$ventas->getTitulo().'"/>';
                break;
            case 3:
                $respuesta= '<object id="halfbanner'.$ventas->getId().'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="468" height="60"><param name="wmode" value="true" /><param name="allowfullscreen" value="false" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://'.$_SERVER['HTTP_HOST'].'/uploads/ventas/'.$ventas->getThumbnail().'" /><embed src="http://'.$_SERVER['HTTP_HOST'].'/uploads/ventas/'.$ventas->getThumbnail().'" type="application/x-shockwave-flash" allowfullscreen="false" allowscriptaccess="always" width="468" height="60" wmode="true"></embed></object>';
                break;
            case 4:
                $respuesta= '<object id="wide_skycraper'.$ventas->getId().'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="160" height="600"><param name="wmode" value="true" /><param name="allowfullscreen" value="false" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://'.$_SERVER['HTTP_HOST'].'/uploads/ventas/'.$ventas->getThumbnail().'" /><embed src="http://'.$_SERVER['HTTP_HOST'].'/uploads/ventas/'.$ventas->getThumbnail().'" type="application/x-shockwave-flash" allowfullscreen="false" allowscriptaccess="always" width="160" height="600" wmode="true"></embed></object>';    
                break;
        }
        return $respuesta;
     }
    public function getTituloCorto($max=15){
        return sfRichSys::cut_string($this->getTitulo(),$max);
    }
    public function getTituloCortoBackend($max=15){
        return substr($this->getTitulo(),0,$max);
    }
     
    public function getContenidoCorto($max=50){
        $texto=strip_tags($this->getContenido());
        return sfRichSys::cut_string($texto,$max);
    }
    
    public function getContenidoMediano($max=700){
        $texto=strip_tags($this->getContenido());
        return sfRichSys::cut_string($texto,$max);
    }
    
     
    public function  delete(Doctrine_Connection $conn = null) {
         $file=$this->getThumbnail();
         if(file_exists(sfConfig::get('sf_upload_dir').'/ventas/'.$file)){
                unlink(sfConfig::get('sf_upload_dir').'/ventas/'.$file);
         }
         if(file_exists(sfConfig::get('sf_upload_dir').'/ventas/thumbnails/'.$file)){
                unlink(sfConfig::get('sf_upload_dir').'/ventas/thumbnails/'.$file);
         }
         parent::delete($conn);
    }
    public function save(Doctrine_Connection $conn = null) {
        /*if(!$this->isNew()){
            $registro_galeria=Doctrine_Core::getTable('VentasGaleria')->getPrimerArchivoPorPublicacion($this->getId());
            if(!$registro_galeria==null){
                $this->setThumbnail($registro_galeria->getThumbnail());
            }
        }*/
        $thumbnail=$this->getThumbnail();
        if(!file_exists(sfConfig::get('sf_upload_dir').'/ventas/thumbnails/'.$thumbnail) && !$thumbnail=="sin_imagen.jpg"){
           if(file_exists(sfConfig::get('sf_upload_dir').'/ventas/'.$thumbnail)){
             sfRichSys::crearThumbnailVentas(sfConfig::get('sf_upload_dir').'/ventas/',$thumbnail,$this->isNew());
           }else{
             $this->setThumbnail("sin_imagen.jpg");  
           } 
        }
        
        if(!$this->getPosition()){
            $this->setPosition(Doctrine_Core::getTable('Ventas')->getMaximo());
        }
        
        parent::save($conn);
    }
    
    public function update(){
        parent::save();
    }
    
    public function getTipoArchivoValid(){
        $archivo=explode(".", $this->getThumbnail());
        $tipos=Doctrine_Core::getTable('VentasGaleria')->getTiposArchivo();
        $resp=1;
        switch ($archivo[1]){
            case "png":
            case "jpg":
            case "gif":
            case "jpeg":    
              $resp=$tipos['Imagen'];
              break;
            case "swf":
              $resp=$tipos['Swf'];
              break;
            default:    
              $resp=$tipos['Link'];
              break;
        }
        return $resp;
    }
}