<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/23 09:51:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sfjerryml',
  'username' => 'root',
  'password' => 'root',
  'persistent' => true,
  'name' => 'doctrine',
)),);
